env:
  browser: true
  es6: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  "max-len": [1, 120, 4],
  "indent": ["error", 4],
  "require-jsdoc": "off",
  "valid-jsdoc": "off",
}
