title: Aristotle Tooltip
description: A highly customisable and easy to use way to insert Aristotle powered definitions to your website!
theme: jekyll-theme-cayman
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
