name: Javascript]
on: [push]
jobs:
  javascript_lint:
    name: Linting
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10 
      - name: Install dependencies
        run: npm install 
      - name: Lint
        run: npm run lint
  javascript_tests:
    needs: javascript_lint
    name: Tests
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test 
