name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: "https://registry.npmjs.org"
      - name: Install NPM Dependencies
        run: npm install
      - name: Create distribution JS
        run: |
          mkdir dist
          cd dist
          npm run build-prod
      - name: Publish to NPM
        run: npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        
